// User
export const LOGIN = "LOGIN";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

// Stories
export const FETCH_STORIES = "FETCH_STORIES";
export const FETCH_STORIES_FAILED = "FETCH_STORIES_FAILED";
export const FETCH_STORIES_BY_AUTHOR = "FETCH_STORIES_BY_AUTHOR";

export const FETCH_STORY_DETAIL = "FETCH_STORY_DETAIL";
export const FETCH_STORY_DETAIL_FAILED = "FETCH_STORY_DETAIL_FAILED";

export const CLAP_FOR_STORY = "CLAP_FOR_STORY";
export const EDIT_STORY = "EDIT_STORY";
export const SHARE_STORY = "SHARE_STORY";
export const CREATE_STORY = "CREATE_STORY";
export const DELETE_STORY = "DELETE_STORY";
export const UPDATE_STORY = "UPDATE_STORY";